server:
  port: 8082

ollama:
  url: http://localhost:11434
  model: sqlcoder:7b
  timeout-seconds: 120

spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    username: default
    password: 
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jdbc:
    show-sql: true

schema:
  cache-ttl-minutes: 5
  candidate-tables: 6
  candidate-columns-per-table: 12

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
